### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Redcozmo** [datapink/robosat.pink#24]
Environment : 
Python 3.6.7
Ubuntu 18.04

```sudo pip3 install -U git+https://github.com/datapink/robosat.pink```

```Traceback (most recent call last):
  File "/usr/local/bin/rsp", line 11, in <module>
    load_entry_point('RoboSat.pink==0.3.5', 'console_scripts', 'rsp')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'robosat_pink'
```

**Comment by ocourtin** [comment]
Thanks for the report !
588a3ce is supposed to fix it.

Also update the Install readme.
