### ISSUE TITLE
albunet has no attribute of resnet error

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#96]
rsp train --train_dataset ds/training/ --eval_dataset ds/validation/ --epochs 5 --out model
RoboSat.pink - train/eval on 1 GPUs, with 4 workers/GPU
---

DataSet Training:        ds/training/
DataSet Eval:            ds/validation/

--- Input tensor
Channel 1:               images - (band:1)
Channel 2:               images - (band:2)
Channel 3:               images - (band:3)
Channel 4:               images - (band:4)

--- Output Classes ---
Class 0:                 Building (1.00)
Class 1:                 Background (0.00)

--- Model ---
nn                       Albunet
loader                   SemSeg
encoder                  resnet50
ts                       (512, 512)

ERROR:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.2-py3.6.egg/robosat_pink/tools/train.py", line 171, in gpu_worker
    shape_in, shape_out, config["model"]["encoder"].lower(), config["train"]
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.2-py3.6.egg/robosat_pink/nn/albunet.py", line 67, in __init__
    weights.data[:, c, :, :] = self.resnet.conv1.weight.data[:, c, :, :]
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Albunet' object has no attribute 'resnet'

**Comment by ocourtin** [comment]
Thanks for the report !

#55af228 should fix it.

To install it from master:
`pip3 install git+https://github.com/datapink/robosat.pink`
