### ISSUE TITLE
robosat_pink.metrics.IOU not found

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#97]
ERROR:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/tools/train.py", line 228, in gpu_worker
    rank, train_loader, config, args.classes_weights, log, csv_train, nn, criterion, "train", epoch, optimizer
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/tools/train.py", line 327, in do_epoch
    _do_epoch()
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/tools/train.py", line 269, in _do_epoch
    metrics = Metrics(config["train"]["metrics"], config["classes"], config=config)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/metrics/core.py", line 13, in __init__
    self.modules = {metric: load_module("robosat_pink.metrics." + metric) for metric in metrics}
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/metrics/core.py", line 13, in <dictcomp>
    self.modules = {metric: load_module("robosat_pink.metrics." + metric) for metric in metrics}
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/RoboSat.pink-0.6.3.dev0-py3.6.egg/robosat_pink/core.py", line 19, in load_module
    module = import_module(module)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'robosat_pink.metrics.IOU'

**Comment by ocourtin** [comment]
It's not OK jaigsingla.
I already told you that assistance can't be provided for free.

You work for a big organization (annual budget > billion USD),
if you don't want to fix your own typos, you should contract an assistance plan to so.

**Comment by jaigsingla** [comment]
I want to fix everything ocourtin and try to use your library to maximum possible extent. I thought there was some fix required but as you are pointing typo issues ; m just checking. thanks
